---
- hosts: "j80"
  gather_facts: no
  collections:
    - ibm.ibm_zos_core
  environment:
      ZOAU_HOME: /zoau
      PATH: /zoau/bin:/java/current8/bin:/spark/spark-current/bin:/mlz/anacondamlz/bin:/usr/lpp/skrb/bin:/usr/lpp/Printsrv/bin:/bin:/usr/sbin:$PATH
      PYTHONPATH: /zoau/lib
      LIBPATH: /zoau/lib
      _BPXK_AUTOCVT: "ON"
  tasks:
    - name: test zos_find
      zos_find:
        patterns: D83DUMP.DYNZOS25.J[ABCDEFGHIJKL89]0.*
      register: response
    - debug: var=response

